#!/bin/bash
mkdir .tmp
ln -s .tmp tmp
cd tmp
mkdir WORKING_dir
cd WORKING_dir
git clone git://github.com/thomhastings/bt5-scripts bt5s
git clone git://github.com/thomhastings/os-scripts f0Ss
git clone git://github.com/thomhastings/attackvector avlx
git clone git://github.com/thomhastings/c0ntempt c0rt
git clone git://github.com/kaneda/kinfe knjx
git clone git://github.com/ksoona/attackvector s00n
git clone git://github.com/thomhastings/dotfiles .dot
cd .dot
sh install.sh
sudo -s
apt-get install htop
